version: 2

macros:
  - name: cents_to_dollars
    description: A macro to convert cents to dollars
    arguments:
      - name: column_name
        type: string
        description: The name of the column you want to convert
      - name: precision
        type: integer
        description: Number of decimal places. Defaults to 2.
  - name: rolling_aggregate
    description: A macro that calculates a rolling aggregate for a given column
    arguments:
      - name: column_name
        type: string
        description: The name of the column you want to aggregate
      - name: partition_by
        type: string
        description: The column to partition by
      - name: order_by
        type: string
        description: The column to order by
      - name: aggregate_fn
        type: string
        description: The aggregate function to use. Defaults to avg.
      - name: n_periods
        type: integer
        description: The number of periods to aggregate over. Defaults to 7.
