version: 2

macros:
  - name: cents_to_dollars
    description: A macro to convert cents to dollars
    arguments:
      - name: column_name
        type: string
        description: The name of the column you want to convert
      - name: precision
        type: integer
        description: Number of decimal places. Defaults to 2.
  - name: rolling_aggregate
    description: A macro that calculates a rolling aggregate for a given column
    arguments:
      - name: column_name
        type: string
        description: The name of the column you want to aggregate
      - name: partition_by
        type: string
        description: The column to partition by
      - name: order_by
        type: string
        description: The column to order by
      - name: aggregate_fn
        type: string
        description: The aggregate function to use. Defaults to avg.
      - name: n_periods
        type: integer
        description: The number of periods to aggregate over. Defaults to 7.
  - name: month
    description: A macro that returns the month of a timestamp or date
    arguments:
      - name: ts
        type: timestamp
        description: The timestamp to extract the month from
  - name: current_month
    description: A macro that returns the current month
  - name: unit_testing_select_table
    description: A macro that returns either the name of the source table to use for unit testing if unit testing is configured (the `unit_testing` var is set) or the name of the actual source table.
    arguments:
      - name: source_table
        type: string
        description: The name of the source table.
      - name: test_table
        description: The name of the table to use for unit testing.
